# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"czech-iso-citation-from-0.1.5","base":"v0.1.5"}]'

oarepo_major_version = "12"

package_oarepo_version = "oarepo-0.1.5"

configuration = '{"name": "citeproc-py-styles", "oarepo": 12, "features": [{"name": "czech-iso-citation-from-0.1.5", "base": "v0.1.5"}], "package": "citeproc-py-styles", "invenio_version": "0.1.5", "version": "0.1.5"}'
